spring:
  profiles:
    active: local
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/agent?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: root
#    password: 123456789
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: never
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/agent
    username: root
    password: 123456789
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch


# 额外的类型推断配置
logging:
  level:
    org.springframework.beans: DEBUG
    com.alibaba.cloud.nacos: WARN
    org.springframework.ai: DEBUG



# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.dswang.aiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8123
  servlet:
    context-path: /api
# MyBatis-Plus 配置
mybatis-plus:
  type-aliases-package: com.dswang.aiagent.entity
  global-config:
    db-config:
      id-type: auto  # 主键自增
      logic-delete-field: deleted  # 逻辑删除字段
      logic-delete-value: 1  # 已删除
      logic-not-delete-value: 0  # 未删除
    banner: false  # 关闭 MyBatis-Plus banner
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL
    cache-enabled: false

