spring:
  profiles:
    active: local
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/agent?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: root
#    password: 123456789
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/agent
    username: root
    password: 123456789
    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:sql/chat_messages.sql
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    mcp:
      client:
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
        sse:
          connections:
            server1:
              url: http://127.0.0.1:8127
        # stdio:
        # servers-configuration: classpath:mcp-servers.json



# 额外的类型推断配置
logging:
  level:
    org.springframework.beans: DEBUG
    com.alibaba.cloud.nacos: WARN
    org.springframework.ai: DEBUG



# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.dswang.aiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8123
  servlet:
    context-path: /api
# MyBatis 配置（用于聊天历史等业务表）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dswang.aiagent.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false


