spring:
  ai:
    mcp:
      server:
        name: image-search-mcp-server
        version: 0.0.1
        type: SYNC
        # stdio
        stdio: true
  # stdio
#  mvc关闭，本地不需要往外暴露端口
  main:
    web-application-type: none
    banner-mode: off
